import Head from "next/head";
import "./globals.css";

export const metadata = {
  title: "creyo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Head>
          <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} />
        </Head>
        {children}
      </body>
    </html>
  );
}
